# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        MainWindow.setMinimumSize(QtCore.QSize(400, 500))
        MainWindow.setMaximumSize(QtCore.QSize(400, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../texture/icontitle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: \'black\';\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 480, 111, 16))
        self.label.setMaximumSize(QtCore.QSize(16777212, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.title_text = QtWidgets.QLabel(self.centralwidget)
        self.title_text.setGeometry(QtCore.QRect(50, 20, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Bulatov SP Demo")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.title_text.setFont(font)
        self.title_text.setMouseTracking(False)
        self.title_text.setTabletTracking(False)
        self.title_text.setAcceptDrops(False)
        self.title_text.setStyleSheet("@font-face {\n"
"    color: rgb(255, 0, 4);\n"
"    font-family: \"Bulatov\"; \n"
"    src: url(\"C:/VASKILL/fonts/BulatovSPDemo.otf\") format(\"truetype\"); \n"
"    font-style: normal; \n"
"    font-weight: normal; \n"
"  } \n"
"\n"
"#title_text{\n"
"    font: 50pt \"Bulatov SP Demo\";\n"
"    color:\'red\';\n"
"    font-style: italic;\n"
"}")
        self.title_text.setObjectName("title_text")
        self.btn_play = QtWidgets.QPushButton(self.centralwidget)
        self.btn_play.setGeometry(QtCore.QRect(150, 260, 81, 81))
        self.btn_play.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_play.setStyleSheet("QPushButton {\n"
"border: 1px solid \'black\';\n"
"border-radius:15px;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    border-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.btn_play.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("texture/icon_play1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_play.setIcon(icon1)
        self.btn_play.setIconSize(QtCore.QSize(90, 90))
        self.btn_play.setFlat(True)
        self.btn_play.setObjectName("btn_play")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 400, 231, 41))
        self.label_2.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 12pt \"Segoe Fluent Icons\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 370, 371, 41))
        self.label_3.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 12pt \"Segoe Fluent Icons\";")
        self.label_3.setObjectName("label_3")
        self.btn_settings = QtWidgets.QPushButton(self.centralwidget)
        self.btn_settings.setGeometry(QtCore.QRect(360, 10, 31, 31))
        font = QtGui.QFont()
        font.setKerning(True)
        self.btn_settings.setFont(font)
        self.btn_settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_settings.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_settings.setStyleSheet("QPushButton{\n"
"border: 1px solid \'black\';\n"
"border-radius:15px;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"border-color: rgb(255, 255, 255);\n"
"}")
        self.btn_settings.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("texture/icon_settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_settings.setIcon(icon2)
        self.btn_settings.setIconSize(QtCore.QSize(30, 30))
        self.btn_settings.setCheckable(False)
        self.btn_settings.setFlat(True)
        self.btn_settings.setObjectName("btn_settings")
        self.title_text_2 = QtWidgets.QLabel(self.centralwidget)
        self.title_text_2.setGeometry(QtCore.QRect(60, 60, 261, 91))
        font = QtGui.QFont()
        font.setFamily("Bulatov SP Demo")
        font.setPointSize(42)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.title_text_2.setFont(font)
        self.title_text_2.setMouseTracking(False)
        self.title_text_2.setTabletTracking(False)
        self.title_text_2.setAcceptDrops(False)
        self.title_text_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background: none;")
        self.title_text_2.setIndent(-1)
        self.title_text_2.setObjectName("title_text_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SKILL"))
        self.label.setText(_translate("MainWindow", "beta-v-0.0.1-design"))
        self.title_text.setText(_translate("MainWindow", "SKILLVA"))
        self.label_2.setText(_translate("MainWindow", "Если вы ещё этого не сделали."))
        self.label_3.setText(_translate("MainWindow", "Просьба ознакомиться с настройками ассистента!"))
        self.title_text_2.setText(_translate("MainWindow", "PROJECT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
